import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import Navigation from "../../components/Navigation";
import Link from "next/link";
import Newsletter from "../../components/Newsletter";
import { Eyebrow, SectionHead, flagFor, type Ground } from "../../components/Page";
import Footer from "../../components/Footer";
import { RandomTestimonials } from "../../components/Testimonials";
import { GoldButton } from "../../components/ui";
import { BOOKS, SERIES, booksInSeries, type Book, type SeriesKey } from "../../constants/Books";

/**
 * Generate metadata for individual book pages
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const book = BOOKS.find((b) => b.slug === slug);

  if (!book) {
    return {
      title: "Book Not Found",
    };
  }

  return {
    title: book.title,
    description: book.description,
    alternates: { canonical: `/books/${book.slug}` },
    openGraph: {
      title: `${book.title} | Ivy Spellman`,
      description: book.description,
      type: "book",
      url: `/books/${book.slug}`,
      // Per-book share card so a shared book link previews with THAT cover.
      // Cards are generated by scripts/generate-og.mjs — re-run after adding a book.
      images: [
        {
          url: `/og/${book.slug}.jpg`,
          width: 1200,
          height: 630,
          alt: `${book.title} — a cozy witch romantic fantasy by Ivy Spellman`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${book.title} | Ivy Spellman`,
      description: book.description,
      images: [`/og/${book.slug}.jpg`],
    },
  };
}

/**
 * Generate static params for all book pages
 */
export function generateStaticParams() {
  return BOOKS.map((book) => ({
    slug: book.slug,
  }));
}

const GROUNDS: Record<SeriesKey, Ground> = { hfh: "plum", birchwood: "emerald" };

/**
 * Book hero: cover as an object on the left, the whole pitch on the right.
 */
function BookHero({ book }: { book: Book }) {
  const series = SERIES.find((s) => s.key === book.series)!;
  const flag = flagFor(book);
  const paragraphs = book.longDescription.split("\n\n");
  return (
    <section className={`jb-sec jb-pagehero jb-${GROUNDS[book.series]}`} data-stars="18">
      <div className="jb-wrap">
        <div className="jb-bookhero">
          <div className="jb-cover ivy-floaty" data-burst>
            <Image src={book.coverImage} alt={`${book.title} by Ivy Spellman`} width={720} height={1100} priority sizes="(max-width: 900px) 260px, 380px" />
            {flag && <span className="flag">{flag}</span>}
          </div>
          <div>
            <Eyebrow>
              <Link href={`/books#${series.anchor}`}>{series.name}</Link> · {book.seriesLabel}
            </Eyebrow>
            <h1>{book.title}</h1>
            <p className="jb-hook">{book.description}</p>
            <div className="jb-body jb-blurb">
              {paragraphs.map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>
            <div className="jb-row">
              {book.buyLink ? (
                <GoldButton as="a" href={book.buyLink} target="_blank" rel="noopener noreferrer">
                  {book.preorder ? "Preorder on Amazon" : "Read it on Amazon"}
                </GoldButton>
              ) : (
                <span className="jb-soon">{book.releaseNote || "Coming soon"}</span>
              )}
              {book.previewLink ? (
                <Link className="jb-ghost" href={book.previewLink}>
                  Read the first chapter
                </Link>
              ) : (
                !book.buyLink && (
                  <Link className="jb-ghost" href="#newsletter">
                    Tell me when it&apos;s out
                  </Link>
                )
              )}
            </div>
            <p className="jb-fine">A cozy witch romantic fantasy with midlife magic and comedy · closed door · happy ending</p>
          </div>
        </div>
      </div>
    </section>
  );
}

/**
 * What this book is / You'll like this if: two soft panels, equal weight.
 */
function BookDetails({ book }: { book: Book }) {
  return (
    <section className="jb-sec jb-ink" style={{ paddingBlock: "90px" }}>
      <div className="jb-wrap jb-two">
        <div className="jb-panel">
          <Eyebrow>What this book is</Eyebrow>
          <ul className="jb-likes">
            {book.whatThisBookIs.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>
        <div className="jb-panel">
          <Eyebrow>You&apos;ll like this if</Eyebrow>
          <ul className="jb-likes">
            {book.youllLikeThisIf.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

/**
 * The series in reading order, current book ringed in gold.
 */
function ReadingOrder({ book }: { book: Book }) {
  const series = SERIES.find((s) => s.key === book.series)!;
  const books = booksInSeries(book.series);
  const idx = books.indexOf(book);
  const next = books[idx + 1];
  return (
    <section className={`jb-sec jb-${book.series === "hfh" ? "navy" : "teal"}`} data-stars="10">
      <div className="jb-wrap">
        <SectionHead
          split
          eyebrow="Reading order"
          title={series.name}
          lede={next ? `Up next: ${next.title}. Every book is a complete romance, so you can also jump in anywhere.` : series.intro}
        />
        <div className="jb-order" style={books.length < 6 ? { gridTemplateColumns: `repeat(${books.length}, minmax(0, 170px))` } : undefined}>
          {books.map((b) => (
            <Link key={b.slug} href={`/books/${b.slug}`} className={b.slug === book.slug ? "here" : undefined} aria-current={b.slug === book.slug ? "page" : undefined}>
              <Image src={b.coverImage} alt={`${b.title} cover`} width={240} height={360} sizes="150px" />
              <span>{b.seriesLabel}</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

/**
 * Single Book Page
 * Dynamic route for individual book details
 */
export default async function SingleBookPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const book = BOOKS.find((b) => b.slug === slug);

  if (!book) {
    notFound();
  }

  const series = SERIES.find((s) => s.key === book.series)!;
  const seriesPosition = book.seriesPosition;

  return (
    <main className="jb bg-ivy-dark min-h-screen">
      {/* Book schema — generated from the same BOOKS entry the page renders,
          so it can never drift from what's on screen. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Book",
                "@id": `https://www.ivyspellman.com/books/${book.slug}#book`,
                name: book.title,
                alternativeHeadline: "A Cozy Witch Romantic Fantasy with Midlife Magic and Comedy",
                author: { "@id": "https://www.ivyspellman.com/#person" },
                url: `https://www.ivyspellman.com/books/${book.slug}`,
                image: `https://www.ivyspellman.com${book.coverImage}`,
                description: book.description,
                abstract: book.longDescription,
                inLanguage: "en-US",
                bookFormat: "https://schema.org/EBook",
                genre: ["Cozy fantasy", "Paranormal romance", "Romantic comedy", "Later in life romance"],
                ...(seriesPosition
                  ? {
                      position: seriesPosition,
                    }
                  : {}),
                isPartOf: {
                  "@type": "BookSeries",
                  "@id": `https://www.ivyspellman.com/#${series.anchor}`,
                  name: series.name,
                },
                ...(book.buyLink
                  ? {
                      offers: {
                        "@type": "Offer",
                        url: book.buyLink,
                        availability: book.comingSoon || book.preorder
                          ? "https://schema.org/PreOrder"
                          : "https://schema.org/InStock",
                      },
                    }
                  : {}),
              },
              {
                "@type": "BreadcrumbList",
                itemListElement: [
                  { "@type": "ListItem", position: 1, name: "Home", item: "https://www.ivyspellman.com" },
                  { "@type": "ListItem", position: 2, name: "Books", item: "https://www.ivyspellman.com/books" },
                  { "@type": "ListItem", position: 3, name: book.title, item: `https://www.ivyspellman.com/books/${book.slug}` },
                ],
              },
            ],
          }),
        }}
      />
      <Navigation />
      <BookHero book={book} />
      <BookDetails book={book} />
      <ReadingOrder book={book} />
      {book.series === "hfh" && (
        <RandomTestimonials title="Whispers from the readers" eyebrow="Five-star reviews of the series opener" ground="teal" />
      )}
      <Newsletter />
      <Footer />
    </main>
  );
}
